project:
  type: website
  render:
    - index.qmd
    - activities.qmd
  resources:
    - data/public/json/**
    - data/public/csv/**
    - assets/generated/**

website:
  title: "Canawler"
  site-url: "https://canawler.com"
  navbar:
    left:
      - href: index.qmd
        text: Progress
      - href: activities.qmd
        text: Activities

format:
  html:
    theme: default
    css: styles.css
    toc: false
